env: "home"
log:
  level: "INFO"
  std_err_level: "INFO"
chain_node: #链节点配置
  chain_id: mychain
  org_id: wx-org1.chainmaker.org
  tls: true
  tls_host: chainmaker.org
  conn_cnt: 10
  remotes:
    - address: 192.168.1.51:12301 #10.200.20.162:12301 #175.6.15.201
      ca_path: asserts/home210u230/crypto-config/wx-org1.chainmaker.org/ca/ca.crt
chain_admin_crts:
  - tls_key_path: "asserts/home210u230/crypto-config/wx-org1.chainmaker.org/user/admin1/admin1.tls.key"
    tls_crt_path: "asserts/home210u230/crypto-config/wx-org1.chainmaker.org/user/admin1/admin1.tls.crt"
  - tls_key_path: "asserts/home210u230/crypto-config/wx-org2.chainmaker.org/user/admin1/admin1.tls.key"
    tls_crt_path: "asserts/home210u230/crypto-config/wx-org2.chainmaker.org/user/admin1/admin1.tls.crt"
  - tls_key_path: "asserts/home210u230/crypto-config/wx-org3.chainmaker.org/user/admin1/admin1.tls.key"
    tls_crt_path: "asserts/home210u230/crypto-config/wx-org3.chainmaker.org/user/admin1/admin1.tls.crt"
  - tls_key_path: "asserts/home210u230/crypto-config/wx-org4.chainmaker.org/user/admin1/admin1.tls.key"
    tls_crt_path: "asserts/home210u230/crypto-config/wx-org4.chainmaker.org/user/admin1/admin1.tls.crt"
client:
  key: "asserts/home210u230/crypto-config/wx-org1.chainmaker.org/user/client1/client1.tls.key"
  crt: "asserts/home210u230/crypto-config/wx-org1.chainmaker.org/user/client1/client1.tls.crt"
  sign_key: "asserts/home210u230/crypto-config/wx-org1.chainmaker.org/user/client1/client1.sign.key"
  sign_crt: "asserts/home210u230/crypto-config/wx-org1.chainmaker.org/user/client1/client1.sign.crt"
